### PR TITLE
fix: treat `InvalidResponse` as connection-invalidating even when `disconnect_on_error=False`

### LINKED ISSUE #4291: PubSub and maintenance-push reads loop forever on `InvalidResponse` because the offending reply is never consumed
## Summary

`Connection.read_response` normally protects callers from a malformed reply by disconnecting: the `except BaseException` handler calls `self.disconnect()`, which drops the parser buffer so the poisoned stream is discarded and the pool reconnects on next use.

Three callers opt out of that with `disconnect_on_error=False` (line numbers against `master` @ `afe6523e`):

- `PubSub.parse_response` — `redis/client.py:1420`
- the pending-push drain inside `Connection.send_command` — `redis/connection.py:1811`
- `_process_pending_invalidations` — `redis/connection.py:2070`

On those paths a protocol-level parse failure is unrecoverable. The parsers rewind the buffer on any exception (`pos = self._buffer.get_pos()` … `except BaseException: self._buffer.rewind(pos)` in `redis/_parsers/resp2.py:13-26`, and the same in `resp3.py`), so the offending reply is not partially consumed — the read position returns to where it started and every byte of the reply stays queued. Combined with no disconnect, the next read re-parses the exact same bytes and raises the exact same error, indefinitely. A subscriber that hits this spins on the error with no way to make progress, and any reply queued behind the bad one is permanently unreachable.

The `send_command` drain site fails differently but from the same cause: its `while ... can_read()` loop only catches `TimeoutError`, so an `InvalidResponse` propagates out of `send_command` while the unread bytes keep `can_read()` true, leaving the connection in the same unusable state on a path where callers expect a send, not a parse error.

The rewind is the right behaviour for an in-band `ResponseError`, which legitimately belongs to a pipeline reply and may need to be re-read. It is the wrong behaviour for a framing violation, where the stream position is no longer trustworthy and preserving it only guarantees the next read fails identically.

## Reproduction

No server needed — a fake socket serves two queued replies, the first of which fails to parse. Run from the redis-py checkout root:

```python
import os
import socket
import sys

sys.path.insert(0, os.getcwd())  # run this from the redis-py checkout root

from redis.connection import Connection


class FakeSocket:
    """Serves a canned byte stream, then behaves like an open-but-idle socket."""

    def __init__(self, data):
        self.data, self.timeout = data, None

    def recv(self, n):
        if not self.data:
            raise socket.timeout("idle")
        chunk, self.data = self.data[:n], self.data[n:]
        return chunk

    def settimeout(self, t):
        self.timeout = t

    def gettimeout(self):
        return self.timeout

    def close(self):
        pass

    def shutdown(self, how):
        pass


# Reply 1 is deeply nested; reply 2 is what the next read should return.
DEPTH = 3000  # on master nothing caps depth, so this must exceed the recursion limit
STREAM = b"*1\r\n" * DEPTH + b"+leaf\r\n" + b"+SECOND\r\n"


def run(label, **kw):
    conn = Connection(protocol=2)
    conn._sock = FakeSocket(STREAM)
    conn._parser.on_connect(conn)
    print(label)
    for i in (1, 2):
        try:
            print(f"  read {i} -> {conn.read_response(**kw)!r}")
        except BaseException as e:
            print(f"  read {i} -> {type(e).__name__}: {str(e)[:50]}")
        buf = conn._parser._buffer
        print(
            f"     is_connected={conn.is_connected} "
            f"unread={'released' if buf is None else buf.unread_bytes()}"
        )


run("default path (disconnect_on_error=True)")
run("pubsub path (disconnect_on_error=False)", disconnect_on_error=False)
```

On `master` (`afe6523e`):

```
default path (disconnect_on_error=True)
  read 1 -> RecursionError: maximum recursion depth exceeded
     is_connected=False unread=released
  read 2 -> AttributeError: 'NoneType' object has no attribute 'readline'
     is_connected=False unread=released
pubsub path (disconnect_on_error=False)
  read 1 -> RecursionError: maximum recursion depth exceeded
     is_connected=True unread=12016
  read 2 -> RecursionError: maximum recursion depth exceeded
     is_connected=True unread=12016
```

The default path disconnects and releases the buffer, so it recovers. The pubsub path keeps the connection open with all 12016 bytes still queued and fails identically on the second read; `+SECOND` is never reached.

(The `AttributeError` on the default path's second read is an artifact of this harness calling `read_response` directly on an already-closed connection. Real callers go through the pool, which reconnects. It is not part of the issue.)

## Relationship to #4144

#4144 adds a `MAX_NESTING_DEPTH` guard so deep nesting raises `InvalidResponse` instead of `RecursionError`. Running the same script against that branch (`DEPTH = 150`, since the guard trips at 101):

```
default path (disconnect_on_error=True)
  read 1 -> InvalidResponse: Response nesting depth exceeded 100
     is_connected=False unread=released
  read 2 -> AttributeError: 'NoneType' object has no attribute 'readline'
     is_connected=False unread=released
pubsub path (disconnect_on_error=False)
  read 1 -> InvalidResponse: Response nesting depth exceeded 100
     is_connected=True unread=616
  read 2 -> InvalidResponse: Response nesting depth exceeded 100
     is_connected=True unread=616
```

**This is not caused by #4144.** The loop is identical before and after; only the exception type changes. #4144 is adjacent context only: it makes the failure cleaner and deterministic — a defined protocol error at a defined depth rather than a stack overflow at an unpredictable one — but it does not make the pubsub path recover, because the cause is the missing invalidation, not the exception type. Nesting depth is just one way to reach a parse failure; any framing violation on these paths behaves the same way.

## Suggested direction

Treat `InvalidResponse` as connection-invalidating even when `disconnect_on_error=False`. A framing violation means the parser can no longer locate reply boundaries in the stream, so the connection is not reusable regardless of what the caller asked for. `disconnect_on_error=False` exists so pubsub can survive *in-band* errors without dropping its subscriptions; it was not intended to keep a connection whose byte stream is no longer parseable.

That turns the failure from permanent into terminal-but-recoverable: one clean error, connection dropped, subscriber reconnects and resubscribes. Handling in the parser instead (consuming and discarding the bad reply rather than rewinding) is not viable — once framing is lost there is no reliable way to find where the next reply begins.

Happy to put up a PR if this direction sounds right.

### PR DESCRIPTION
**Pull request by UgaTheDev**
Fixes #4291

## Problem

`Connection.read_response` protects callers from a malformed reply by disconnecting, which drops the parser buffer so the poisoned stream is discarded and the pool reconnects. Three callers opt out with `disconnect_on_error=False`:

- `PubSub.parse_response` (`redis/client.py:1420`)
- the pending-push drain in `Connection.send_command` (`redis/connection.py:1811`)
- `_process_pending_invalidations` (`redis/connection.py:2070`)

On those paths a protocol-level parse failure is unrecoverable. The parsers rewind the buffer on any exception (`resp2.py:13-26`, same in `resp3.py`), so the offending reply is *not* consumed — the read position returns to where it started and every byte stays queued. Combined with no disconnect, the next read re-parses the same bytes and raises the same error, indefinitely. A subscriber spins on the error with no way to make progress, and any reply queued behind the bad one is permanently unreachable.

## Fix

Catch `InvalidResponse` ahead of the general `except BaseException` handler and disconnect regardless of `disconnect_on_error`, in both `redis/connection.py` and `redis/asyncio/connection.py`.

The reasoning is a semantic distinction between two error classes that happen to share a code path:

- An in-band `ResponseError` legitimately belongs to a reply. The stream stays framed, the error may need re-reading, and `disconnect_on_error=False` plus the rewind exist to serve exactly this — pubsub surviving an in-band error without dropping its subscriptions. Unchanged by this PR.
- An `InvalidResponse` is a framing violation: the parser can no longer locate reply boundaries, so the stream position is untrustworthy. Preserving it only guarantees the next read fails identically. Handling this in the parser (consuming and discarding the bad reply instead of rewinding) is not viable — once framing is lost there is no reliable way to find where the next reply begins.

`InvalidResponse` and `ResponseError` are siblings under `RedisError` with no subclasses, so the new handler cannot catch an in-band error.

The failure changes from permanent to terminal-but-recoverable: one clean error, connection dropped, subscriber reconnects and resubscribes via the `on_connect` callback.

## Behavior change

`InvalidResponse` still propagates to the caller on all three paths — only the connection state changes. Per-path effect:

- **PubSub**: previously an infinite loop on the same error. Now the error surfaces once and the connection is dropped; the next `get_message`/`listen` reconnects (`conn.connect()` on the blocking path, `conn.can_read()` on the non-blocking one, both of which reconnect a closed connection) and resubscribes. `InvalidResponse` is not in the retry-supported errors, so it is not silently retried.
- **The two `while can_read()` drain loops** (`send_command` pending-push drain, `_process_pending_invalidations`): these previously left the connection open with unread bytes on a framing error. They now lose the connection. Both already let a non-`TimeoutError` propagate, so the loops exited via the exception either way; the difference is that the connection is no longer handed back in an unusable state. `can_read()` reconnects a closed connection, so neither loop can spin.

Callers that relied on keeping a connection alive across a framing violation will see it dropped — that is the intent, since such a connection could not produce a correct reply again.

## Tests

`tests/test_connection.py::TestInvalidResponseInvalidatesConnection` — fake-socket repro from the issue, no server needed:

- framing error on the pubsub call signature (`disconnect_on_error=False, push_request=True`) disconnects and releases the buffer — **fails on master**
- pubsub path recovers on the next read after reconnecting instead of re-raising forever — **fails on master**
- in-band `ResponseError` on the same path still does *not* disconnect, and the next reply is readable — guards the rewind's purpose
- framing error still disconnects on the default path

`tests/test_asyncio/test_connection.py::test_invalid_response_always_disconnects` — parametrized over `disconnect_on_error`, asserts `disconnect(nowait=True)` in both cases; the `False` case fails on master.

Full runs of `tests/test_connection.py`, `tests/test_asyncio/test_connection.py`, `tests/test_pubsub.py`, `tests/test_asyncio/test_pubsub.py`: 477 passed, with the same 8 pre-existing cluster-dependent failures as on master (471 passed baseline; the delta is the 6 new tests).

## Relationship to #4144

Independent. #4144 makes deep nesting raise `InvalidResponse` instead of `RecursionError`; the loop described here is identical before and after it, because the cause is the missing invalidation rather than the exception type. This PR does make #4144's error recoverable on the pubsub path.

---

> [!NOTE]
> **Medium Risk**
> Changes when connections are torn down on pub/sub, push drains, and CLIENT TRACKING cache paths; misclassification could drop healthy connections, though ValueError from push handlers is explicitly excluded.
> 
> **Overview**
> Fixes **#4291** by treating certain parser failures as connection-fatal even when callers pass **`disconnect_on_error=False`** (notably PubSub and invalidation drains).
> 
> Introduces **`UNRECOVERABLE_PARSE_ERRORS`** (`InvalidResponse`, `UnicodeDecodeError`, `RecursionError`) and handles them in sync/async **`read_response`** so the connection is always disconnected—avoiding infinite re-parse loops when poisoned bytes stay in the buffer. In-band **`ResponseError`** and push-handler **`ValueError`** behavior is unchanged.
> 
> Pure-Python RESP2/RESP3 parsers now map bad numeric frames (`:abc`, `$xyz`, `*abc`, etc.) to **`InvalidResponse`** via **`_parse_int`** / **`_parse_float`** instead of raising **`ValueError`**.
> 
> **`CacheProxyConnection`** factors invalidation draining into **`_drain_invalidations`** and **flushes the client cache** when that drain hits an unrecoverable parse error, since the raw disconnect bypasses the proxy’s normal flush.
> 
> Broad regression tests cover framing errors, binary pub/sub with **`decode_responses=True`**, deep nesting, malformed lengths, and cache flush on drain failure.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 6bd11ebdecc7f47882cc0b840a15be595e886746. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

**Review by petyaslavova — CHANGES_REQUESTED** [review]
Hey @UgaTheDev, thank you for your contribution!

The defect is real and `Connection.read_response` is the right place to fix it - it also covers `SentinelManagedConnection.read_response`, which defaults to `disconnect_on_error=False` and is a fourth opt-out site you did not list. Before merging, though, the predicate needs to be widened, because `InvalidResponse` is not what the reachable cases raise:

- The reproduction in #4291 raises `RecursionError` on current master, so this patch does not fix it unless #4144 lands first. That case is real, not synthetic: `EVAL "local t={} local c=t for i=1,3000 do local n={} c[1]=n c=n end return t" 0` makes Redis emit exactly your fake stream (12004 bytes), and through a sentinel-managed connection it is on the ordinary command path.
- The realistic pubsub trigger is `Encoder.decode` at the tail of `_read_response`, which runs after the cursor has passed the payload. A `decode_responses=True` subscriber receiving a binary `PUBLISH` payload raises `UnicodeDecodeError` and loops exactly as described, on both parser backends. Please add that as a regression test.

Keep the allowlist shape rather than inverting to "disconnect unless resumable" - `test_connection_parse_response_resume` drives resume with a bare `BaseException` under `disconnect_on_error=False` and would break.

One correction to the rationale, since it is now in the code comments: the rewind and `disconnect_on_error` come from #2510 ("Make PythonParser resumable") and #2695, so they exist to re-parse an interrupted read, not to survive in-band errors. An in-band `ResponseError` is returned as a value and purged, never rewound.

Also needed: an async test that exercises the pubsub read path and asserts the next read is clean (the async parser re-parses via `self._pos = 0`, not the sync rewind), and a rebase for the end-of-file conflicts in the two test files.

File: redis/_parsers/base.py [hunk 1]
```diff
@@ -40,6 +41,22 @@
...
+# these regardless of disconnect_on_error, or the caller loops forever (#4291).
+#
+# - InvalidResponse: unknown reply type byte, or hiredis' own nesting limit.
+# - UnicodeDecodeError: Encoder.decode at the tail of _read_response, reached
+#   only after the payload has been consumed (decode_responses=True subscriber
+#   receiving a binary PUBLISH payload).
+# - RecursionError: deeply nested aggregate replies exhaust the stack in the
+#   pure-Python parsers. #4144 turns this into InvalidResponse at a bounded
+#   depth; until then, catching it here is what stops the loop.
+UNRECOVERABLE_PARSE_ERRORS = (InvalidResponse, UnicodeDecodeError, RecursionError)
```
[the remark this answers is not in the document]
Comment (UgaTheDev) [reply redis/_parsers/base.py]: Confirmed, and fixed in a44aad3c. A malformed integer, bulk length or aggregate length (`:abc\r\n`, `$xyz\r\n`, `*abc\r\n`) raises `ValueError` from `int(...)` in `resp2.py` and `resp3.py`, and that type was not in `UNRECOVERABLE_PARSE_ERRORS`, so under `disconnect_on_error=False` the parser rewound to the same frame on every read. hiredis is not affected: it raises `InvalidResponse` (already in the tuple) rather than a Python `ValueError`.

The fix adds `ValueError` to the tuple, keeping the allowlist shape rather than inverting it. The only other `int()` in the read path parses a server-sent port in a maintenance push notification, so a `ValueError` there is also a framing fault, not a recoverable condition.

Regression tests added for sync and async: malformed integer, bulk-length and array-length frames each leave the connection disconnected, the next read after reconnect is clean, and a valid integer frame leaves the connection up. All existing tests in both connection test files still pass.

File: redis/_parsers/base.py [hunk 2]
```diff
@@ -40,6 +41,24 @@
...
+# - InvalidResponse: unknown reply type byte, or hiredis' own nesting limit.
+# - UnicodeDecodeError: Encoder.decode at the tail of _read_response, reached
+#   only after the payload has been consumed (decode_responses=True subscriber
+#   receiving a binary PUBLISH payload).
+# - RecursionError: deeply nested aggregate replies exhaust the stack in the
+#   pure-Python parsers. #4144 turns this into InvalidResponse at a bounded
+#   depth; until then, catching it here is what stops the loop.
+# - ValueError: malformed numeric frames (e.g., `:abc\r\n`) where int(response)
+#   fails when parsing integer, bulk length, or aggregate length fields.
+UNRECOVERABLE_PARSE_ERRORS = (InvalidResponse, UnicodeDecodeError, RecursionError, ValueError)
```
[the remark this answers is not in the document]
Comment (UgaTheDev) [reply redis/_parsers/base.py]: Good catch, and agreed: the `disconnect_on_error=False` opt-out exists precisely so a handler exception does not tear down the subscription, and with hiredis the push frame is already consumed by the time the handler runs. Fixed in a62dc413 the way you suggest.

- `ValueError` is out of `UNRECOVERABLE_PARSE_ERRORS` again. The tuple is back to `(InvalidResponse, UnicodeDecodeError, RecursionError)`.
- The pure-Python RESP2/RESP3 parsers now go through `_parse_int` / `_parse_float`, which turn a non-numeric integer, bulk length, aggregate length or double field into `InvalidResponse("Protocol Error: <raw line>")`. Same message shape as the existing unknown-type-byte path, so the malformed-frame tests from a44aad3c now assert `InvalidResponse`.
- New `TestPushHandlerValueErrorKeepsConnection` (hiredis, RESP3): a `pubsub_push_handler_func` that raises `ValueError` propagates, `conn.is_connected` stays `True`, and the next queued `+SECOND` frame is still readable. That test fails with `ValueError` in the tuple and passes with this commit.

One thing worth noting for completeness: with the pure-Python RESP3 parser the same scenario behaves differently, because `read_response` rewinds the buffer on any exception and the next read replays the push frame into the handler again. That is pre-existing and out of scope here, but it is why the new test pins hiredis rather than parametrizing over all three parsers.

**Review by petyaslavova — CHANGES_REQUESTED** [review]
Thanks for the follow-ups. The widened predicate is what I was after, and the measured per-backend table settles the reachability question. The async mirror and the cache flush on the invalidation drain both look right to me.

Two things before merge: please rebase onto master, and get the integration matrix green - the head now routes every RESP numeric field through `_parse_int`, so I want a full protocol x legacy_responses run rather than just the bot check. Also, the malformed-numeric test classes parametrize over a single parser; please extend them to the hiredis parsers, which report these frames as `InvalidResponse`, so backend parity is covered.

On the two open bot threads: the cache-flush one on `CacheProxyConnection.read_response` is a real gap, but it predates this PR - a raw disconnect already skips the proxy flush on every `disconnect_on_error=True` error path - so we will track it separately rather than grow this PR. The push-handler one is also real for hiredis, where the frame is consumed before the handler runs, though on the pure-Python parser your change improves that case rather than regressing it. If you would like to close it properly, converting the parsers' own decode failures to `InvalidResponse` at the decode sites and dropping `UnicodeDecodeError` from the tuple would do it; I am fine merging without that.

The `_parse_int`/`_parse_float` conversion is beyond what I asked for, but I am happy to keep it: without it a desynced stream yielding a non-numeric length still loops, and plain `ValueError` cannot go in the tuple because a push handler may raise it.

**Comment by UgaTheDev** [comment]
Thanks @petyaslavova. All three items are in, head is now `739fe971`.

**Rebased onto master.** The conflicts were in `redis/connection.py` and `redis/asyncio/connection.py`, where master had meanwhile added `add_debug_log_for_connection_failure` and an `as e` binding to the `BaseException` handler. I resolved by keeping master's version and wiring the new handler into the same logging, so the sync `UNRECOVERABLE_PARSE_ERRORS` clause now reads:

```python
except UNRECOVERABLE_PARSE_ERRORS as e:
    # ... (unchanged rationale)
    add_debug_log_for_connection_failure(self, e, "reading response")
    self.disconnect()
    raise
```

That keeps the new path consistent with the neighbouring handlers rather than being the one that logs nothing. Branch is 0 commits behind master.

**Hiredis parity on the malformed-numeric classes.** You were right that they parametrized over a single parser. Both classes now cover all three backends, and since hiredis reports these frames as `InvalidResponse` (the same exception the tests already asserted) no test body changed, only the parametrize list:

- `TestMalformedNumericFrameInvalidatesConnection`: `_RESP2Parser`, `_RESP3Parser`, `_HiredisParser`
- `TestAsyncMalformedNumericFrameInvalidatesConnection`: `_AsyncRESP2Parser`, `_AsyncRESP3Parser`, `_AsyncHiredisParser`

The hiredis params carry the same `skipif(not HIREDIS_AVAILABLE)` guard `TestDeeplyNestedReplyInvalidatesConnection` already uses. 30 tests pass locally against hiredis 3.4.1.

**Integration matrix.** Over to CI for the full protocol x legacy_responses run, since I do not have the sentinel/cluster/SSL setup locally. For what it is worth, `tests/test_connection.py` and `tests/test_asyncio/test_connection.py` are 255 passed / 2 skipped / 0 failed here; the only local failures are `test_cache.py` cases that need live sentinel and cluster servers (`MasterNotFoundError`). Happy to chase anything the matrix turns up.

On the two bot threads, agreed on both counts, and I am content to leave the `CacheProxyConnection` flush and the hiredis push-handler decode conversion out of this PR as you suggested.

**Comment by UgaTheDev** [comment]
@petyaslavova Rebased onto current master (`55288722`) — clean, no conflicts, branch is 0 commits behind. The malformed-numeric classes now parametrize over all three backends: `TestMalformedNumericFrameInvalidatesConnection` over `_RESP2Parser`/`_RESP3Parser`/`_HiredisParser` and `TestAsyncMalformedNumericFrameInvalidatesConnection` over the three async equivalents, with the hiredis params carrying the same `skipif(not HIREDIS_AVAILABLE)` guard `TestDeeplyNestedReplyInvalidatesConnection` already uses; no test body changed, since hiredis reports these frames as `InvalidResponse` too. With hiredis 3.4.1 installed those are 30 passed / 0 skipped, and `tests/test_connection.py tests/test_asyncio/test_connection.py` together are 261 passed / 2 skipped. On the matrix: every workflow on this PR is sitting at `action_required` rather than having run, so it needs a maintainer to approve the workflow run before I can act on any result.
