### ISSUE TITLE
'Redis' object has no attribute 'sentinel_masters'

### ISSUE THREAD

**Issue by benimohit** [redis/redis-py#1724]
Hi,
It was working till the version 3.5.3 and after updating the Redis to 4.0.1. 
I see this error 'Redis' object has no attribute 'sentinel_masters'. 
 ```
File "/RedisLibrary.py", line 50, in _get_nodes
    master_node = sentinel.discover_master(self.service_name)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/redis/sentinel.py", line 234, in discover_master
    masters = sentinel.sentinel_masters()
```
Is this some sort of bug in the newer version ?
I see that some of the code has been shifted to SentinelCommands class and it's not been extended by Redis class instead its been extended by the Sentinel class. Not sure how it is supposed to work. 
Thanks in advance.

**Comment by chayim** [comment]
Duplicate of #1714
