### ISSUE TITLE
parse_info() fails to parse a list

### ISSUE THREAD

**Issue by nveloso** [redis/redis-py#1510]
**Version**:

- redis-py = 2.10.6
- server redis_version = 2.4.16
- Python 3.8.9 on Ubuntu 16

**Description**:
```
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    main()
  File "test.py", line 30, in scan
    resp = r.info()
  File "/usr/local/venv/lib/python3.8/site-packages/redis/client.py", line 760, in info
    return self.execute_command('INFO')
  File "/usr/local/venv/lib/python3.8/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/venv/lib/python3.8/site-packages/redis/client.py", line 682, in parse_response
    return self.response_callbacks[command_name](response, **options)
  File "/usr/local/venv/lib/python3.8/site-packages/redis/client.py", line 96, in parse_info
    response = nativestr(response)
  File "/usr/local/venv/lib/python3.8/site-packages/redis/_compat.py", line 154, in nativestr
    return x if isinstance(x, str) else x.decode('utf-8', 'replace')
AttributeError: 'list' object has no attribute 'decode'
```
It seems that older servers like version 2.4.16 sends information with array format instead of a string format.
I'm using an older version of redis-py but I checked the source code of the latest version of redis-py and the bug is still there.
I was able to fix checking if the `response` variable that `parse_info()` receives is a list and if so transform into a bytes string:
```
def parse_info(response):
    "Parse the result of Redis's INFO command into a Python dict"
    if isinstance(response, list):
        response = b'\r\n'.join(response)
    info = {}
    response = nativestr(response)
    ...
```

**Comment by chayim** [comment]
Closing - this works in redis-py 3.5.3, and redis-py 2.x is unsupported.

**Comment by Slasat** [comment]
Got this error on 3.5.3, should I upgrade to latest and hope for the best?
<img width="1190" alt="изображение" src="https://user-images.githubusercontent.com/49529856/208631314-38cf1c13-1008-4201-b76a-5665f2e9e940.png">
<img width="296" alt="изображение" src="https://user-images.githubusercontent.com/49529856/208631407-00a612ed-a2ed-450a-91a0-dab61251f686.png">
