### ISSUE TITLE
Regression in 5.0.1: AttributeError: 'NoneType' object has no attribute 'feed'

### ISSUE THREAD

**Issue by PoByBolek** [redis/redis-py#2967]
### Version
- redis-py: 5.0.1
- redis: 7.0.12

### Platform
- Python 3.10.11 on Windows 11

### Description
This is probably a duplicate of #2349, in which case I'd like to re-open that issue, but I got the same error today with redis-py 5.0.1 (worked fine in 5.0.0):

```
Traceback (most recent call last):
  File "C:\Users\PoByBolek\redis-bug\cache.py", line 137, in _get_raw_data
    return redis.hget(self._name, b'data'), None, None,
  File "C:\Users\PoByBolek\redis-bug\venv\lib\site-packages\redis\commands\core.py", line 4946, in hget
    return self.execute_command("HGET", name, key)
  File "C:\Users\PoByBolek\redis-bug\venv\lib\site-packages\redis\client.py", line 536, in execute_command
    return conn.retry.call_with_retry(
  File "C:\Users\PoByBolek\redis-bug\venv\lib\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
  File "C:\Users\PoByBolek\redis-bug\venv\lib\site-packages\redis\client.py", line 537, in <lambda>
    lambda: self._send_command_parse_response(
  File "C:\Users\PoByBolek\redis-bug\venv\lib\site-packages\redis\client.py", line 513, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "C:\Users\PoByBolek\redis-bug\venv\lib\site-packages\redis\client.py", line 553, in parse_response
    response = connection.read_response()
  File "C:\Users\PoByBolek\redis-bug\venv\lib\site-packages\redis\connection.py", line 500, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "C:\Users\PoByBolek\redis-bug\venv\lib\site-packages\redis\_parsers\hiredis.py", line 124, in read_response
    self.read_from_socket()
  File "C:\Users\PoByBolek\redis-bug\venv\lib\site-packages\redis\_parsers\hiredis.py", line 87, in read_from_socket
    self._reader.feed(self._buffer, 0, bufflen)
AttributeError: 'NoneType' object has no attribute 'feed'
```

**Comment by PoByBolek** [comment]
I've added some code that hopefully helps reproducing this issue in case anyone cares.

**Comment by petyaslavova** [comment]
Issue is reproducible with latest code - I was able to reproduce the last exception exampple.

**Comment by alexon1234** [comment]
Reproduced with

```
hiredis                        3.2.1
redis                          5.3.1
```

**Comment by vogre** [comment]
Can confirm this happens when calling `redis.close()` or `with redis:` when using multi-threading with the same client. A possible workaround is to centralize the closing of the client after the `thread.join()`, but it would be nicer to have a proper exception, since current solution seems not-quite thread safe (for `close()`).

**Comment by petyaslavova** [comment]
> Can confirm this happens when calling `redis.close()` or `with redis:` when using multi-threading with the same client. A possible workaround is to centralize the closing of the client after the `thread.join()`, but it would be nicer to have a proper exception, since current solution seems not-quite thread safe (for `close()`).

In this case, this is the expected behaviour. I didn't notice the `with redis:` part when I looked at this earlier. 
`close` is expected to close all clients' connections and release the resources. 
The correct usage is to call `close` the client outside the thread execution, after all threads have completed.
So, I'm closing this issue for now. Feel free to reopen it if you need further assistance.
