### PR TITLE
Fix #2581 UnixDomainSocketConnection' object has no attribute '_command_packer'

### LINKED ISSUE #2581: 'UnixDomainSocketConnection' object has no attribute '_command_packer'
**Version**: v4.5.0

**Platform**: Debian Bullseye using Python v3.9.2

**Description**: 
The following code which used to work on up to and including v4.4.2 now crashes with the stack trace below on v4.5.0.

```python
redis_conn = redis.Redis(
        unix_socket_path="/var/run/redis/redis-server.sock",
        decode_responses=True)
redis_conn.ping()
```

```
Traceback (most recent call last):
  File "<redacted>", line 142, in main
    redis_conn.ping()
  File "/usr/local/lib/python3.9/dist-packages/redis/commands/core.py", line 1194, in ping
    return self.execute_command("PING", **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/redis/client.py", line 1258, in execute_command
    return conn.retry.call_with_retry(
  File "/usr/local/lib/python3.9/dist-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/local/lib/python3.9/dist-packages/redis/client.py", line 1259, in <lambda>
    lambda: self._send_command_parse_response(
  File "/usr/local/lib/python3.9/dist-packages/redis/client.py", line 1234, in _send_command_parse_response
    conn.send_command(*args)
  File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 916, in send_command
    self._command_packer.pack(*args),
AttributeError: 'UnixDomainSocketConnection' object has no attribute '_command_packer'
```

### PR DESCRIPTION
**Pull request by prokazov**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `$ tox` pass with this change (including linting)?
- [x] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [x] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [ ] Was the change added to CHANGES file?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

Apparently there is no end-to-end tests for Unix sockets
so automation didn't catch it. I assume that setting up
the domain sockets reliably in dockerized/tox environment is not that easy.
Added test for pack_command specifically.

### CODE REVIEW

**Review by dvora-h — APPROVED** [review]

**Comment by woutdenolf** [comment]
I can confirm this fixes the issue.

**Comment by dwighthubbard** [comment]
I have confirmed this happens with redis 4.5.2, it isn't occurring with Redis 5.0.0.  So this appears to be an issue with the redis package and I'm going to close this issue.
