### ISSUE TITLE
Stderr backtrace caused by `redis.client.Redis.__del__` on process exit.

### ISSUE THREAD

**Issue by byron-lambda** [redis/redis-py#3014]
**Version**: 5.0.1

**Platform**: Python 3.8.18 on Ubuntu 20.04

**Description**: Backtrace to stderr on process exit due to `redis.client.Redis.__del__()`

Here is the trace:
```
Exception ignored in: <function Redis.__del__ at 0x7fcf29e50ca0>
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/redis/client.py", line 491, in __del__
  File "/venv/lib/python3.8/site-packages/redis/client.py", line 506, in close
  File "/venv/lib/python3.8/site-packages/redis/connection.py", line 1155, in disconnect
  File "/venv/lib/python3.8/site-packages/redis/connection.py", line 1062, in _checkpid
AttributeError: 'NoneType' object has no attribute 'getpid'
```

Occurs due to unloaded globals being referenced in methods called in destructors on process exit. See warning in Python docs [here](https://docs.python.org/3.8/reference/datamodel.html#object.__del__)

This can be fixed in a couple of ways:
1. Add an exception handler to `redis.client.Redis.__del__()` as it appears has been done in many other destructors (https://github.com/redis/redis-py/blob/d3a3ada03e080f39144807c9fbe44876c40e0548/redis/connection.py#L226 for example)
2. Add references to required globals to the `redis.connection.ConnectionPool` class and call via the references. The globals that require references in are `os.getpid` and `chain` (from `itertools`) afaict.

NOTE: It is quite hard to come up with a small piece of code to reproduce this issue as it is caused by a race in the unload order at exit. I'll try to come up with something reliable if req'd.

NOTE: The issue is triggered by https://github.com/redis/redis-py/blob/d3a3ada03e080f39144807c9fbe44876c40e0548/redis/client.py#L506 which was recently introduced in https://github.com/redis/redis-py/commit/012f7cf7d2950e8241eb5705e7cdd83b09370ba4

**Comment by diogosilva30** [comment]
Can confirm this behaviour with version `5.0.1` with Django. I get this error when the development server restarts

**Comment by Alucido** [comment]
Can confirm this behaviour with version `5.0.8`, Python 3.9, when running `pytest` test suite opening a Redis Client in a subclass of the `beam.DoFn` class, as part of its `setup` method. The error is reproduced when the test suite ends and the client is closed.

**Comment by noirbee** [comment]
I've opened https://github.com/redis/redis-py/pull/3397 after encountering this issue following a ddtrace update (probably due to the module loading / patching shenanigans it performs for libraries it wants to monkey-patch).

Thanks @byron-lambda for opening this issue in the first place, and pointing me in the right direction !

**Comment by AlexPetul** [comment]
See the same behavior with python==3.12.9 and redis==5.2.0. 
I ended up subclassing ```redis.Redis``` and overriding ```__del__``` method. Might be not the best solution, but it works:

```python
import json
from uuid import UUID

import redis

from users.caching.base import UserMetadataCache


class Redis(redis.Redis):
    def __del__(self):
        """Release the connection.

        This is an overriden method, that bypasses the exception raise,
        when the `os` module was unloaded before the client's __del__ method was called.
        This can happen on process exit (for example Django hot reload).
        """
        try:
            self.close()
        except AttributeError as exc:
            if exc.name != "getpid":
                raise


class UserMetadataRedisCache(UserMetadataCache):

    def __init__(self, host: str, port: int = 6379) -> None:
        self.client = Redis(host=host, port=port, db=0)

    def set(self, user_id: UUID, data: dict) -> None:
        self.client.set(str(user_id), json.dumps(data))

    def delete(self, user_id: UUID) -> None:
        self.client.delete(str(user_id))

```

**Comment by Lyndon-prequel** [comment]
I ran into this issue too.  To make it easier for others to figure out if they're affected, I created a common reliability enumeration (CRE). You can preview the rule [here](https://play.prequel.dev/?data=EwBmFYFoQFk0AqBGEAucxUGYkDpgAcMAWgAQCiASpQPKWkCGADk7gO4D2ATgNYCmXXFz4ATAJYBnUpFIBBAC7yuYgEYBXeX3Jcu3VKQDkAOQ4A7PggCeTPgdIcVAKz4BjeaQAWDKaY6NFyuqahgDmfPJMYiIGAFAIXAwufCqJPKQAFAC2HBLuwkmm7i4MADYlpCXe8gCUqDGkpABiYiV8pABEAPTMTJ2cvAISnZnhyi4SuEyW7QA0FWLmpABsSHMLpC4cZa7y9Q2MbAxieaKSAPouJWJ8hbgLAGYc6dV7za0dnWoSXJ0lHMUlX6qTpTeQeMxYXBIJCdCTHPiQJipBhhIbCcRDbyWUwuMQcTqXa63KazeaLFAATmAa1MpAeHD2DWE8jUXFpDEOx1IEj4JXuuD4AA9XBo%2BBcOJlMgxTCJ0u0AJJGRo0dovBpvNpdL4-P4AoEqEGWMEQqEwuGaRHI1GddGSboSbG4-GbUzmNx40yTaZzK6LYAU8A00hheRnPgANxuob%2BHCYjNIkREpAAvNzefyzjHWCHE88YgolKpRdpdFx9MYzBZrLZ7E4dp5vKRfP5C0E2gYc1EDEA&rule=E4VwNgpgzgXAUAWgAQGNgXkrSCWATGJAYQCUBRBAJgAZKBWBa6gFgEY5skoIA3CYHABcAnoQDMHbIKGRC6PDigIADsNRgcEAHaCkAMwCGOMFCQB3IQAskAQUGCBAIxCCIZYMAD2wc5e1J0EG48JAM0TyhTAyhhLRQkbyRlLxRoUxRPHQgAD0EoSSwUA1cAc29RVDC-FS9HSABbAtCXS29CAAV0AEcQCDAmvGg0HGVpTMIAHyasZABJLQCIBSVVJB46ADpsgBouSwMBLRLQrhwjyCQSJcV1TR1Q8MjQmLikQWiAa1NEqBBHZM8qUi0EqC3QvzAujOmE4SGQAAM7A4cM5XO4vMBCAByLEAOUyEAAKsJlBAcQlHAArCAoXT7UxaTyhexOFwQJA4koQQTKfA4%2BEbaZwpCEyw3ES8opgMBqQEoEDAUxmPwLQR%2BW7aXSJDJaLQ0sYLZSeTxgXCmQLBB5eJ56bxfBI%2BZX%2BXiapBgY3KVCZVy5M1uiKCXbQUkoHAGaVqM7PWLxPTAAz1CBmO3fHz1cDSAFAqBnY7cQQgZRQQWcIpBDBIKaw4VY%2BSKFRqBxhe1q9lhaR8JAu%2B7uzyegxaEJZtJIWYAEVwqvVOr1tJwmSSxrAG1HehOV2WGvuNwtS0nJwUej0-Fdw6eiWiMben1CelcPlbDpwJTO4a7fB7Hr9ZT1uzO960N8dR9XQNA%2Bdl4W4MA9A2AB9XtlHhJBHBpTxE1MeF8T1eFdjLHMjiQSC%2Bhg%2BCPQ2LkeXwAAKABKJDBCZeNFDbBYkVZNEPG8EspAMEpYCFZA63yatBOuFZhAEpJhDVTJJMvOJJPTSERhSNJc0k4CckEOSWRRNl%2BAxSSPkZMwtAQRRfggJp6iEZ9innLRJkkmweE8fA9gOXNLjErc8itCJTDPbhU2jV53igD4kBKLxC2LSSrjQCBinZFANE1UwzhzQYuD%2BIKQUScsvSyXIEAMMwDnZI0TTikSkAAVW4QihI2eTQ08DYiEyWcDXaJckIUdBaRlXA13qAdeK8pTMwuZNgHAxUkDGrQQHDGVuM4ZA6uUaKDGyhi3nVZRihQPwQj4RUHISNchIbJAqO4dl2hIJAAGIxGoVg6Bo9bFmPdA4mgGENqQSx7CLGAAHoIZfNU-g2DJ6ghoSkbEhsIYs3ooAh97WGYF6MdQ%2BpEx0BBWAADgATjoZgxDJygxAAdkk0GeVgKGYcsOGEZR5YefrVQIeUcAwGxj66CaAxlGUDQigNfjasAxM5FR1QhSwc6c3GDkkAAPgAXiQTZqA2ahdgAHkNjZWBNrE1aK94zn4XEEwrSXlCaHB6iO2lCCCiG1XQXaEHdKVvM3TTfXdJ5IF2rz9tAHRPfZHJUlGBzhOwT3vcEABlDJ0EIcXOBs6QSnszI8%2B8CtmCadAjWAPJCApyRE3ePBigMIGkA%2BM4CCSbpen6Th8EIXForJ5gAHE6FxAAxVg9BsEAADYACFBFXsQSmYMcmnpSxxBsHPV8JdoSi0SxcRAABpOqyHaPRr4ATWEAAJZgoBKFBr4ALUsH%2BADqKAiCCB-mTKAWgACKuI8BdHqHQHAAA1JoXJHJIHYFgUAsgmj5i7lgbsgg8HYCgJ4BUqRCCJQ2O6EoGwbqq2rGNQQJ0iEzEWFybI2INgACo2J6Q4hibEeICTElJOSTwVJ9Qg2iEgRkzJkSonZJybkvI8A4m4ViIAA) or run it against your logs [here](https://github.com/prequel-dev/preq).
